language: generic

sudo: required

services:
    - docker

script:
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash .travis-build.sh $DOCKER_IMAGE

env:
    - DOCKER_IMAGE=centos:7
    - DOCKER_IMAGE=fedora:28
    - DOCKER_IMAGE=fedora:29

before_deploy:
    - openssl aes-256-cbc -K $encrypted_9980bae86343_key -iv $encrypted_9980bae86343_iv -in .copr.enc -out .copr -d

deploy:
    skip_cleanup: true
    provider: script
    script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest /bin/sh -c "dnf install -y copr-cli && copr-cli --config .copr build --chroot epel-7-x86_64 --chroot epel-8-x86_64 --chroot fedora-28-x86_64 --chroot fedora-29-x86_64 --nowait simc/stable eccodes.spec"
    on:
        branch: master
        condition: $DOCKER_IMAGE = centos:7
